import type {Metadata} from 'next';
import {Montserrat} from 'next/font/google';
import './globals.css';
import React from "react";
import ReduxProvider from "@/store/ReduxProvider";
import AuthInitializer from "@components/AuthInitializer";

const montserrat = Montserrat({
    variable: '--font-montserrat',
    subsets: ['latin', 'cyrillic'],
    weight: ['400', '500', '700'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body className={montserrat.className}>
        <ReduxProvider>
            <AuthInitializer/>
            {children}
        </ReduxProvider>
        </body>
        </html>
    );
}
