import type {Metadata} from 'next';
import {Montserrat} from 'next/font/google';
import './globals.css';
import React from "react";
import ReduxProvider from "@/store/ReduxProvider";
import {store} from "next/dist/build/output/store";

const montserrat = Montserrat({
    variable: '--font-montserrat',
    subsets: ['latin', 'cyrillic'],
    weight: ['400', '500', '700'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReduxProvider >
            <html lang="en">
            <body
                className= {montserrat.className}
            >
            {children}
            </body>
            </html>
        </ReduxProvider>
    );
}
